##### imports

In [1]:
from __future__ import print_function
import torch

##### Construct a 5x3 matrix, uninitialized:

In [2]:
x = torch.Tensor(5, 3)
print(x)


 0.0000e+00  0.0000e+00  3.1952e-29
-2.0000e+00  5.6052e-45  0.0000e+00
 1.5046e-36  0.0000e+00  3.2032e-29
 1.5846e+29  3.2009e-29 -1.5846e+29
 2.8026e-45  0.0000e+00  0.0000e+00
[torch.FloatTensor of size 5x3]



##### Construct a randomly initialized matrix

In [3]:
x = torch.rand(5,3)
print(x)


 0.0258  0.7200  0.8241
 0.2460  0.3469  0.4750
 0.8807  0.6457  0.4253
 0.3676  0.2473  0.7910
 0.3801  0.1605  0.3230
[torch.FloatTensor of size 5x3]



##### Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


In [7]:
# addition syntax 1
y = torch.rand(5,3)
print(y)
print(x+y)


 0.3503  0.4465  0.2551
 0.6054  0.8866  0.8681
 0.2111  0.0155  0.0287
 0.0133  0.9181  0.9972
 0.3340  0.4540  0.4150
[torch.FloatTensor of size 5x3]


 0.3761  1.1665  1.0791
 0.8515  1.2335  1.3431
 1.0918  0.6611  0.4540
 0.3809  1.1654  1.7882
 0.7140  0.6144  0.7380
[torch.FloatTensor of size 5x3]



In [8]:
# addition syntax 2
print(torch.add(x,y))


 0.3761  1.1665  1.0791
 0.8515  1.2335  1.3431
 1.0918  0.6611  0.4540
 0.3809  1.1654  1.7882
 0.7140  0.6144  0.7380
[torch.FloatTensor of size 5x3]



In [11]:
# addition syntax 3
result = torch.Tensor(5,3)
print(result)
torch.add(x, y, out=result)
print(result)


1.00000e-43 *
  0.0000  0.0000  0.0000
  0.0000  0.0561  0.5605
  1.5975  1.4153  1.6115
  1.6395  1.5134  1.6255
  0.5745  0.0140  0.0000
[torch.FloatTensor of size 5x3]


 0.3761  1.1665  1.0791
 0.8515  1.2335  1.3431
 1.0918  0.6611  0.4540
 0.3809  1.1654  1.7882
 0.7140  0.6144  0.7380
[torch.FloatTensor of size 5x3]



In [12]:
# addition syntax 4
# in place addition
print(y)
y.add_(x)
print(y)


 0.3503  0.4465  0.2551
 0.6054  0.8866  0.8681
 0.2111  0.0155  0.0287
 0.0133  0.9181  0.9972
 0.3340  0.4540  0.4150
[torch.FloatTensor of size 5x3]


 0.3761  1.1665  1.0791
 0.8515  1.2335  1.3431
 1.0918  0.6611  0.4540
 0.3809  1.1654  1.7882
 0.7140  0.6144  0.7380
[torch.FloatTensor of size 5x3]



In [13]:
# numpy like operation can be done
print(x[:,1])


 0.7200
 0.3469
 0.6457
 0.2473
 0.1605
[torch.FloatTensor of size 5]



In [14]:
# tensor to numpy
a = torch.ones(5,2)
print(a)


 1  1
 1  1
 1  1
 1  1
 1  1
[torch.FloatTensor of size 5x2]



In [15]:
b = a.numpy()
print(b)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


In [16]:
a.add_(1)
print(a)
print(b)


 2  2
 2  2
 2  2
 2  2
 2  2
[torch.FloatTensor of size 5x2]

[[ 2.  2.]
 [ 2.  2.]
 [ 2.  2.]
 [ 2.  2.]
 [ 2.  2.]]


In [19]:
# numpy to tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)
np.add(a,1,out=a)
print(a)
print(b)

[ 1.  1.  1.  1.  1.]

 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [23]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

### Autograd

In [24]:
from torch.autograd import Variable

In [25]:
# create a variable
x = Variable(torch.ones(2, 2), requires_grad=True)
print(x)

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [26]:
# operation on variable
y = x + 2
print(y)

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]



In [27]:
print(y.creator)

In [28]:
# more operation on variable
z = y * y * 3
out = z.mean()
print(z, out)

Variable containing:
 27  27
 27  27
[torch.FloatTensor of size 2x2]
 Variable containing:
 27
[torch.FloatTensor of size 1]



### gradients

In [29]:
out.backward()

In [32]:
print(x.grad)

Variable containing:
 4.5000  4.5000
 4.5000  4.5000
[torch.FloatTensor of size 2x2]



In [38]:
# other example
x = torch.randn(3)
x = Variable(x, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

Variable containing:
  283.6788
-1027.4819
  440.8908
[torch.FloatTensor of size 3]



In [39]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)

print(x.grad)

Variable containing:
  51.2000
 512.0000
   0.0512
[torch.FloatTensor of size 3]



## Neural Networks

In [40]:
from net import Net

In [41]:
net = Net()
print(net)

Net (
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear (400 -> 120)
  (fc2): Linear (120 -> 84)
  (fc3): Linear (84 -> 10)
)


In [42]:
params = list(net.parameters())
print(len(params))
print(params[0].size())  # conv1's .weight

10
torch.Size([6, 1, 5, 5])


In [43]:
input = Variable(torch.randn(1, 1, 32, 32))
out = net(input)
print(out)

Variable containing:
 0.0276 -0.0172 -0.1026  0.0613  0.0106 -0.0609  0.0529 -0.0048  0.1250 -0.0016
[torch.FloatTensor of size 1x10]



In [44]:
net.zero_grad()
out.backward(torch.randn(1, 10))

In [45]:
print(out)

Variable containing:
 0.0276 -0.0172 -0.1026  0.0613  0.0106 -0.0609  0.0529 -0.0048  0.1250 -0.0016
[torch.FloatTensor of size 1x10]



In [47]:
print(input.grad)

None


### loss
e.g. simple mean square error

In [49]:
output = net(input)
target = Variable(torch.arange(1, 11))  # a dummy target, for example
import torch.nn as nn
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

Variable containing:
 38.2919
[torch.FloatTensor of size 1]



In [50]:
# for illustration
print(loss.creator)  # MSELoss
print(loss.creator.previous_functions[0][0])  # Linear
print(loss.creator.previous_functions[0][0].previous_functions[0][0])  # ReLU

### backprop


In [51]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
Variable containing:
 0
 0
 0
 0
 0
 0
[torch.FloatTensor of size 6]

conv1.bias.grad after backward
Variable containing:
 0.1412
 0.0356
 0.0103
-0.0279
-0.0306
-0.1748
[torch.FloatTensor of size 6]



In [52]:
# update the weights using optimizer
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()    # Does the update

